name: Build UtilityStartAllBack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild utility-startallback.sln /p:Configuration=Release

    - name: Upload compiled exe
      uses: actions/upload-artifact@v4
      with:
        name: UtilityStartAllBack
        path: |
          **/bin/Release/*.exe
